### ISSUE TITLE
[Question] How does the Free Monoid steps get generated?

### ISSUE THREAD

**Issue by NickSeagull** [rightfold/lands#1]
I've been checking the source code, and I see that there is a `Render`  DSL which gets interpreted and renders the graphics. What I don't understand is, how does one program using this DSL? Maybe I'm confused and its not the use for it?

For instance, I'm using a Free Monad for my game and in [this function](https://github.com/NickSeagull/quorant/blob/master/src/Quorant/Game.hs#L15):

```haskell
gameLoop :: Game input ()
gameLoop = do
    drawDisplay
    input <- getInput :: Game input input
    processInput input
    gameLoop
```

I program my loop using a Free Monad. But theorically, if I made `getInput` to store user's input in some `State`, so it returned `()` it could be a Free Monoid, right?
The thing is, if I wanted to do a condition to it like:

```haskell
gameLoop :: Game input ()
gameLoop = do
    drawDisplay
    getInput
    ifM inputIsQuit
        quit
        processInput input
    gameLoop
```

Here `inputIsQuit` would return an `m Bool` so it couldnt be a Free Monoid, so getting to the point:

**How is a Free Monoid useful for a video game, and when is it better to use instead of a Free Monad?** 😁

**Comment by rightfold** [comment]
The DSL is only for rendering, and rendering is output only. Input handling happens before rendering.

**Comment by NickSeagull** [comment]
Great thanks!
